services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_transcendance
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/backend/src
      - ./backend/prisma:/backend/prisma
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "file:/backend/prisma/dev.db"
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      CHOKIDAR_USEPOLLING: true
